### PR TITLE
feat(FirebaseListObservable): implement remove method

### LINKED ISSUE #85: Implement FirebaseListObservable.remove
Part of #41 

Remove should accept either a string for the key of the item to remove, the snapshot of the item to be removed, or the unwrapped snapshot of the item to remove (presuming the unwrapped snapshot has a $key field).

```typescript
interface FirebaseListObservable {
  remove(item:string | FirebaseDataSnapshot | AFUnwrappedSnapshot) => Promise<void>;
}
```

I'd prefer not to allow removing by index, unless there's a compelling use case to do so. The index carries less confidence of correctness than an item's key, since an item's index can change randomly.

### PR DESCRIPTION
**Pull request by jeffbcross**
Accepts either a key, a snapshot, a reference, or an 
unwrapped Snapshot, to remove the item from the list.

Closes #85

Part of #41

### CODE REVIEW

**Comment by jeffbcross** [comment]
I updated some of the tests to push objects instead of strings, since now I'm adding a `$key` property to unwrapped objects.

**Comment by jeffbcross** [comment]
@davideast @katowulf any pitfalls with assigning the `$key` the way I'm doing in this PR? It requires that all values be objects (i.e. not strings or numbers).

**Comment by katowulf** [comment]
It's the same conclusion David, Jacob, and I came to for AngularFire. Primitive values were stored in a `$value` attribute and we assume all values are objects. This makes extending them, adding toJSON() methods, and other things much more simpler in the long run (no guessing the type), so it ends up being fairly flexible, although what happens to primitives isn't immediately intuitive to new devs.

**Comment by katowulf** [comment]
Honestly, I've been looking forward to ES6 and TypeScript, because I wanted to go ahead and class all the records stored in collections and just keep the data under a property (e.g. `$value` or `getValue()`) anyway, as this would have made dev and usage simpler and more robust.

**Comment by jeffbcross** [comment]
@katowulf cool, I'll use that `$value` strategy in this implementation.

I'm using an interface instead of a class to represent the unwrapped snapshot, so we still have the benefits of POJS template bindings.

```typescript
export interface AFUnwrappedDataSnapshot {
  $key: string;
  $value?: string | number | boolean;
}
```

**Comment by jeffbcross** [comment]
Updated PR.

**Pull request merged**
