### PR TITLE
feat(functions): Allow configuration of Functions Emulator Origin

### PR DESCRIPTION
**Pull request by jamesdaniels**
### Checklist

   - Issue number for this PR: #nnn (required)
   - Docs included?: (yes/no; required for all API/functional changes) 
   - Test units included?: (yes/no; required) 
   - In a clean directory, `yarn install`, `yarn test` run successfully? (yes/no; required)

### Description

Allow AngularFireFunctions to point to the Cloud Functions Emulator. This increases minimum requirement of Firebase to 5.5.7.

### Code sample

Point callable Functions to the Cloud Function emulator by adding the  `FunctionsEmulatorOriginToken` to the `providers` section of your `NgModule`.

```ts
import { NgModule } from '@angular/core';
import { AngularFireFunctionsModule, FunctionsEmulatorOriginToken } from '@angular/fire/functions';
@NgModule({
  imports: [
    ...
    AngularFireFunctionsModule,
    ...
  ],
  ...
  providers: [
   { provide: FunctionsEmulatorOriginToken, useValue: 'http://localhost:5005' }
  ]
})
export class AppModule {}
```

### CODE REVIEW

**Comment by jamesdaniels** [comment]
@davideast Ready for review. Don't merge, if approved; as I'm targeting this for the 5.2 release.

**Comment by Splaktar** [comment]
This would be nice to have! Looks like it needs a rebase tho.

**Comment by thefliik** [comment]
@jamesdaniels currently, if you are using a custom domain with firebase functions (via firebase hosting) I don't believe `@angular/fire` has any way of specifying the origin for callable functions requests (I believe you are forced to send callable function requests to the `cloudfunctions.net` domain). If a function is doing something like setting a cookie on the client, the domain used when calling the function matters.

This PR looks like it addresses that need, but, if so, the name of the token `FunctionsEmulatorOriginToken` is inappropriate. Might I suggest renaming it to simply `FunctionsOriginToken`.

**Comment by jamesdaniels** [comment]
@thefliik I like that idea, I'm also not loving the `*Token` pattern. Might align more with Angular here and name it `FUNCTIONS_ORIGIN` rather than `FunctionsOriginToken`

**Comment by hiepxanh** [comment]
i love this

**Pull request merged**
