### PR TITLE
Tweak to allow querying

### PR DESCRIPTION
**Pull request by mip1983**
This is just a small tweak to allow database.list to accept a firebase query as an arg.
This might help toward issue #16.

This allows me to do things like this:

`return this.af.database.list(this.ref.child("navigation").orderByChild("order")) as Observable<MenuItem[]>;`

### CODE REVIEW

**Comment by mip1983** [comment]
I signed it!

**Comment by davideast** [comment]
Ah nice catch! We have a broken build right now (not your fault). After it's fixed we'll re-run and merge.

**Comment by davideast** [comment]
Hey @mip1983! There does seem to be an error with your change. Can you try running the tests locally and see what's going on? Thanks 😎

**Comment by mip1983** [comment]
Hi @davideast , I'm having some trouble running the tests locally, karma's not playing ball yet on my machine. I've put in a fix based on the test output from Travis.

I've also run 'npm run build_bundle' to create the js files in the dist folder. I'm not sure if that's required or if any of the other npm build commands need running?

**Comment by tomdegoede** [comment]
@mip1983 This currently breaks the push and remove methods on FirebaseListObservable. (probably update as well).

A solution might be calling ref.ref() [here](https://github.com/mip1983/angularfire2/blob/c18c256c763bfb2903a0f02c8743daff772e8793/src/utils/firebase_list_factory.ts#L58) when ref is a FirebaseQuery instance. (Haven't tested this).

**Comment by mip1983** [comment]
@tomdegoede Ok, I'll have a look when I can. I'm beginning to wonder if 'Firebase' and 'FirebaseQuery' need to be two different things.

**Comment by davideast** [comment]
Hey @mip1983! While your fix is 100% right, your PR seems to have added a bunch of files into the repo. 

We're working on interactive querying (see #145), and this changes the code you've committed a bit. So to avoid merge conflicts I'm going to close this PR. 

While this contribution didn't land, I want to thank you so much for taking your time to work on AngularFire. Please do keep checking in and checking out help wanted tags. 😄

**Pull request closed without merging**
