### PR TITLE
chore - update the typings.json content as required by latest version of typings tool

### PR DESCRIPTION
**Pull request by ksachdeva**
Also use index.d.ts in package.json & tsconfig.json files

### CODE REVIEW

**Comment by davideast** [comment]
Hi @ksachdeva,

Thanks for taking the time to send in the PR. We have a contributing policy of opening up an issue first. As you can see there are merge conflicts because we are actively developing this library. By opening a request first we can communicate what should fixed so there are minimal conflicts.

Can you give more details about the change you made with typings?

**Comment by ksachdeva** [comment]
Hi David,

Regarding the typings it is the upgrade to 1.X version of typings tool. The 1.X requires a different syntax for typings.json file. 

Did not know about creating the issue first policy. Will follow that from onwards

Regards
Kapil

**Comment by davideast** [comment]
Hey @ksachdeva. We are in the middle of another PR to fix the provider data, can you remove that change, fix the spacing in `package.json` and `tsconfig.json`, and also fix the merge conflicts (they should be minor)?

After that we'll be able to merge your PR!

**Comment by davideast** [comment]
Closing due to inactivity and other updates.

**Pull request closed without merging**
