### PR TITLE
BREAKING CHANGE Firebase@5.0.1 DocChanges is now a method

### PR DESCRIPTION
**Pull request by paulstelzer**
Bug fix for firebase@5.0.1: "QuerySnapshot.docChanges() is now a method "

### CODE REVIEW

**Comment by ChargerIIC** [comment]
The build succeeds locally when I try it. Could this be a false positive from Travis CI?

**Comment by jamesdaniels** [comment]
@paulstelzer thanks for the patch. I think you'll need to bump the firebase version in the `package.json` to get it to succeed in Travis.

**Comment by lakerko** [comment]
Is this available now please? And could you maybe show an example of how to use it? Thank you.

**Comment by paulstelzer** [comment]
@jamesdaniels Updated the firebase and firebase/firestore version in package.json to latest, but travis still could not complete - so I think I have to remove my PR

**Comment by ChargerIIC** [comment]
@paulstelzer Looks like you updated the package.json but not the package-lock.json file. Seems silly, but the Travis CI script insists on having both updated.

**Pull request closed without merging**
