### PR TITLE
Fix H1 in Markdown

### PR DESCRIPTION
**Pull request by mikedory**
Fixing spacing in an H1 so that Github's Markdown parser renders it appropriately.

### Checklist

   - Issue number for this PR: n/a/
   - Docs included?: n/a
   - Test units included?: n/a
   - e2e tests included?: n/a
   - In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? n/a

### Description

Fixing spacing in an H1 so that Github's Markdown parser renders it appropriately.

### Code sample

n/a

### CODE REVIEW

**Comment by markgoho** [comment]
This doc is pretty outdated. I'm not sure it should even be included in this repo anymore.

**Comment by mikedory** [comment]
Fair enough — just hit a weird display issue while reading the docs. Feel free to accept the pull or torch it as you see fit!

**Comment by markgoho** [comment]
Sorry @mikedory I deleted my previous comment because it actually applied to your other PR #997 -- sorry about that.

**Comment by mikedory** [comment]
@markgoho no worries! Same "feel free to do whatever" comment applies to that one too. =)

**Pull request merged**
