### PR TITLE
a handful of package and publish chores

### PR DESCRIPTION
**Pull request by jeffbcross**

### CODE REVIEW

**Comment by jeffbcross** [comment]
@davideast care to review?

**Comment by kazkis** [comment]
hi @jeffbcross 
since when angular2 was in beta the package.json was like this
`"angular2": ">=2.0.0-beta.14 <2.0.0-rc.1",` (include all beta versions from the beta-14 up to the first release candidate)

can't we do something similar for the rc versions like this
`"@angular/core": ">=2.0.0-rc.2 <2.0.0"` (include all rc versions from the rc.2 up to the final release)

instead of listing all the possible future rc versions?

(I'm trying to learn through [https://semver.npmjs.com/](https://semver.npmjs.com/)  :worried:)

**Comment by davideast** [comment]
LGTM 👍

**Comment by Khalid-Nowaf** [comment]
I have the same problem as #320 and #325 . but I think the problem is fixed now, So how can I use npm to install the latest changes from the master branch ?

**Comment by nunoarruda** [comment]
@Khalid-Nowaf I use `"angularfire2": "git://github.com/angular/angularfire2.git#master"`

**Pull request merged**
