### PR TITLE
Update firebase.app.module.ts

### PR DESCRIPTION
**Pull request by MingyuJeon**
### Checklist

   - Issue number for this PR: #1571 (required)
   - Docs included?: no
   - Test units included?: no
   - In a clean directory, `yarn install`, `yarn test` run successfully? yes

### Description

**Bug fix**
```
Class FirebaseApp incorrectly implements interface 'FirebaseApp'.
Property `automaticDataCollectionEnabled` is missing in type FirebaseApp 
```
### Code sample

**firebase.app.module.d.ts**
```
import {InjectionToken} from '@angular/core';
import {FirebaseAppConfig} from './';
import {FirebaseApp as FBApp} from '@firebase/app-types';
import {FirebaseAuth} from '@firebase/auth-types';
import {FirebaseDatabase} from '@firebase/database-types';
import {FirebaseMessaging} from '@firebase/messaging-types';
import {FirebaseStorage} from '@firebase/storage-types';
import {FirebaseFirestore} from '@firebase/firestore-types';

export declare const FirebaseAppConfigToken: InjectionToken<FirebaseAppConfig>;

export declare class FirebaseApp implements FBApp {
  name: string;
  automaticDataCollectionEnabled: boolean; // add here
  options: {};
  auth: () => FirebaseAuth;
  database: () => FirebaseDatabase;
  messaging: () => FirebaseMessaging;
  storage: () => FirebaseStorage;
  delete: () => Promise<any>;
  firestore: () => FirebaseFirestore;
}

export declare function _firebaseAppFactory(config: FirebaseAppConfig, appName?: string): FirebaseApp;
```

### CODE REVIEW

**Comment by MingyuJeon** [comment]
Even though you change `firebase.app.module.ts` to this, the error could happen because ionic pro npm install again when it build an app. So, if the error occurs, you would need to downgrade to `@firebase/app@0.1.10`.

**Comment by jamesdaniels** [comment]
Thanks for the quick fix.

**Comment by jamesdaniels** [comment]
@sarunint I'll support the new Firebase initialize method style, which takes `automaticDataCollectionEnabled` as an argument in a follow on PR. Will want to bump the req in the package.json for that one.

**Comment by wroobell94** [comment]
The problem still occurs in Angular CLI. 
I'm not using firebase/app only angularfire2 and firebase to manage firestore calls. 

Same error.

**Comment by sarunint** [comment]
That's because the fix in this PR has not been released yet.

**Comment by software770** [comment]
Is it realesed today ? How Do I fix it now ?

**Pull request merged**
