### PR TITLE
Update Angular2 dep. to support Betas until RC1

### LINKED ISSUE #135: Support developing on latest Angular 2 Betas
It seems tedious to fork and update this library each time a new beta comes out.  I have a PR inbound to support all further Betas until the RC.  If there is some specific reason why we are targeting a specific beta at a time, let me know and I'll abandon.

### PR DESCRIPTION
**Pull request by gamebox**
Closes #135

### CODE REVIEW

**Comment by gamebox** [comment]
Investigating test failure, getting similar error locally MacOS X 10.11 with Chrome 50 Stable on master.

**Comment by davideast** [comment]
This is a good idea! Our build is currently breaking, but that's not your fault. After I get it fixed I'll merge 👍

**Comment by gamebox** [comment]
Oh man, I spent 2 or 3 hours trying to debug this.  I'm so happy to hear I didn't destroy anything.  Let me know if there is anything I can do to help.

**Comment by davideast** [comment]
All green! Thanks for the PR.

**Pull request merged**
