### PR TITLE
Make the $key and $exists properties non-enumerable

### LINKED ISSUE #302: Remove $key and $value on calls to set
We're adding these properties to objects returned from firebase, but if someone modifies these objects and then calls set the set call will fail because these are invalid properties in a firebase object.
I think we should automatically remove these properties if they're present in a set call since they aren't valid firebase keys anyways.

### PR DESCRIPTION
**Pull request by meDavid**
Making these keys non enumerable makes sure that you can use Object.keys() and Object.values on the unwrapped value without having the extra properties to account for.

This would also resolve #302

### CODE REVIEW

**Comment by davideast** [comment]
@meDavid This is awesome! Can you write a unit test to verify the behavior?

**Comment by katowulf** [comment]
Good stuff!  c[_]c[_]

**Comment by davideast** [comment]
@katowulf Angular 2 only supports back to IE10.

**Comment by katowulf** [comment]
Perfect. We just need test units then, @meDavid

**Comment by katowulf** [comment]
Any chance we can get the test units in for this?

**Comment by meDavid** [comment]
@katowulf Yes, I will make it happen in the next couple of days

**Comment by theunreal** [comment]
Very useful. Any updates regards this?

**Comment by meDavid** [comment]
@katowulf @davideast I updated the pullrequest with an additional test to see if the behavior is correct. If you have any suggestions for improvements, let me know.

**Comment by davideast** [comment]
@meDavid Thank you so much! There appears to be a merge conflict, however. Can you get that sorted out and then we'll do a review to merge in?

**Comment by meDavid** [comment]
@davideast  I don't see any merge conflict, only a rebase conflict but I don't know how to resolve that. Any pointers?

**Comment by davideast** [comment]
@meDavid I'm not 100% either, but you can try to follow [this guide here](https://help.github.com/articles/resolving-merge-conflicts-after-a-git-rebase/) or simply store your changes locally, resync the fork/delete it and re-fork, and then reapply your changes.

**Comment by davideast** [comment]
@meDavid Any updates on this? I ran into this recently myself and I just deleted my fork and moved my changes over to the new one. You lose history, but it works.

**Comment by byrondover** [comment]
Patched these changes in locally, works brilliantly! C'mon @meDavid, new branch and new PR to quick fix, you deserve the commit creds.

**Comment by meDavid** [comment]
@byrondover I'll find some time this weekend

**Comment by meDavid** [comment]
superseded by https://github.com/angular/angularfire2/pull/787

**Pull request closed without merging**
