### PR TITLE
Update 1-install-and-setup.md

### PR DESCRIPTION
**Pull request by JimTheMan**
spelling correction: borke -> broke

### CODE REVIEW

**Comment by JimTheMan** [comment]
I signed it!

**Comment by gianpaj** [comment]
duplicate of #544 - which apparently is on purpose

**Comment by yashmurty** [comment]
**Borke :** Broken in a sudden, unexpected manner at a critical time.
_It's launch day and the webserver's fuc*in BORKE_
Very punny! :smiling_imp:

**Comment by katowulf** [comment]
@JimTheMan thanks for this! Leaving as-is based on the comments here and in linked PR.

**Comment by HomeboxJim** [comment]
Well imo as someone who doesn't know that borke is a word (probably 95-99% of people reading this README) is just looks like an obvious error. Then subconsciously you start doubting this github  project altogether including the code!

You should as least make the word "borke" link out to that urban dictionary link for the definition of borke to make it clear that it is intentional. :)

**Comment by JimTheMan** [comment]
Well imo as someone who doesn't know that borke is a word (probably 95-99% of people reading this README) is just looks like an obvious error. Then subconsciously you start doubting this github project altogether including the code!

**Comment by gianpaj** [comment]
@JimTheMan I wouldn't go that far. Using an uncommon word or a funny/quirky word makes the entire project dubious?
Maybe the word should be between double quotes or in italics.

PS: I'm unsubscribing from following discussions about the single word in a README file.
Let's spend more time fixing bugs, and improving the quality of the project and its code rather than arguing about semantics. ✌️

**Comment by JimTheMan** [comment]
Lol I guess you are right, but yeah quotes would be nice.

On Sep 27, 2016 3:38 PM, "Gianfranco Palumbo" <notifications@github.com>
wrote:
>
> @JimTheMan I wouldn't go that far. Using an uncommon word or a
funny/quirky word makes the entire project dubious?
> Maybe the word should be between double quotes or in italics.
>
> PS: I'm unsubscribing from following discussions about the single word in
a README file.
> Let's spend more time fixing bugs, and improving the quality of the
project and its code rather than arguing about semantics. ✌️

**Pull request closed without merging**
