### PR TITLE
firebase3.d.ts location change

### PR DESCRIPTION
**Pull request by mabdelfattah**

### CODE REVIEW

**Comment by mabdelfattah** [comment]
I signed it!

--
Best,
Mahmoud M. Abdel-Fattah
http://about.me/mabdelfattah

On August 1, 2016 at 9:31:35 PM, googlebot (notifications@github.com) wrote:

Thanks for your pull request. It looks like this may be your first
contribution to a Google open source project. Before we can look at your
pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 *Please visit https://cla.developers.google.com/
<https://cla.developers.google.com/> to sign.*

Once you've signed, please reply here (e.g. I signed it!) and we'll verify.
Thanks.
------------------------------

   - If you've already signed a CLA, it's possible we don't have your
   GitHub username or you're using a different email address. Check your
   existing CLA data <https://cla.developers.google.com/clas> and verify
   that your email is set on your git commits
   <https://help.github.com/articles/setting-your-email-in-git/>.
   - If you signed the CLA as a corporation, please let us know the
   company's name.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular/angularfire2/pull/402#issuecomment-236649609>,
or mute the thread

**Comment by jeffbcross** [comment]
firebase3.d.ts should be in the root of the package that gets published to npm. Is it not?

**Comment by mabdelfattah** [comment]
it is not!

**Comment by jeffbcross** [comment]
It is on npmcdn for beta.2: https://npmcdn.com/angularfire2@2.0.0-beta.2/firebase3.d.ts

What version are you seeing this behavior?

**Comment by Splaktar** [comment]
I am seeing `firebase3.d.ts` in the root of the package when using `2.0.0-beta.2` as well. So this PR doesn't seem to be needed. 

Perhaps @mabdelfattah could open an issue to figure out the problem that he is having?

**Comment by Splaktar** [comment]
Also note that it looks like Firebase 3.2.1 includes the official typings:
https://github.com/angular/angularfire2/issues/390

**Comment by davideast** [comment]
Closing as we are moving to the types in the npm module

**Pull request closed without merging**
