### PR TITLE
WIP Rxjs 6 and angular 6

### PR DESCRIPTION
**Pull request by kawamoto**
I've try to update rxjs to v6.x https://github.com/angular/angularfire2/issues/1538

It pass a build, and seems work fine with my tiny app which is using authentication and realtime db.
Test is failed and I can not figure out why. it seems injection in test does not working as expected.

I hope it helps maintainers or someone else.

### Checklist

   - Issue number for this PR: #nnn (required)
     - #1538
   - Docs included?: (yes/no; required for all API/functional changes) 
     - no
   - Test units included?: (yes/no; required) 
     - no
   - In a clean directory, `yarn install`, `yarn test` run successfully? (yes/no; required)
     - no

### CODE REVIEW

**Comment by davideast** [comment]
Hi @kawamoto! I really appreciate you taking the time to migrate us over to RxJS 6. However, I do not recommend doing it all in one big PR. It's really hard to review and increases the chances of creating bugs. How about you partition this PR into multiple ones based off each Firebase feature? Start with changing one module and after we merge that in move on to the next. Does that sound good?

**Comment by robertbaker** [comment]
@kawamoto Do you mind if I take this over or are you working on the changes?

**Comment by kawamoto** [comment]
Hi @davideast. thank you for respond. I basically agree with your suggestion. but with this topic, I think it's hard to split PR simply. without whole of those changes, even building does not work. maybe it's better to update latest RxJS 5.x and migrate operators first. after that, I guess updating process looks more simple. wdyt?

**Comment by kawamoto** [comment]
Hi @robertbaker , I'm happy with someone solve this 👍 I guess I can not take time for this PR in this week.

**Comment by robertbaker** [comment]
@davideast I would prefer to dp Rx6 has 1 clean PR, because I don't think mixing Rx5 is a good option. It also allows a beta release for people to test. I'm happy to work on this and chat if needed. Let me know your thoughts.

**Comment by juanpablodelatorre** [comment]
Is there any new information about this? Can we expect this to be working any time soon?

**Comment by davideast** [comment]
@kawamoto @robertbaker I appreciate your efforts, but this is a big change that has to be carefully done. This PR already has 48 changed files this is too large to review without missing any changes. At Google we measure the size of CLs (our version of PRs) and this would be an XL CL. It is strongly recommend to keep your CLs at small to medium so they are easier to review. XL CLs do happen, but it is always advisable to avoid them.

You can continue to upgrade the pipeable operators per feature using RxJS 5.5+. That means there would be one PR per feature to migrate to pipeable operators. When we're off the side effect import operators we can then do a PR to upgrade to RxJS 6 and fix and changed import paths. 

Calling in @BenLesh to see if this is a sound strategy.

**Comment by jymdman** [comment]
@davideast I have made a couple of pull request to update this lib to pipeable operators. I hope this is what you are looking for to get this thing going! :)

**Comment by davideast** [comment]
Update: I noticed that @jamesdaniels pulled the PRs in from @jymdman, which were nice and small! I needed my coffee before trying to get up to speed with the latest PRs.

**Pull request closed without merging**
