### PR TITLE
Ionic2 angular fire2 auth

### PR DESCRIPTION
**Pull request by mukesh51**
### Checklist

   - Issue number for this PR: #590
   - Docs included?: Yes 
   - Test units included?: N/A 
   - e2e tests included?: N/A
   - In a clean directory, N/A

### Description

Created a walkthrough for Auth on Ionic/Cordova as per issue #590

### CODE REVIEW

**Comment by fabien0102** [comment]
Great! I see just an issue, with ionic you need deal with browser and cordova case for facebook login.

This is my service version for facebook native connect:

```javascript
import { Facebook } from 'ionic-native';
import firebase from 'firebase';

/**
   * Login with native facebook API.
   * 
   * @return firebase.Promise<FirebaseAuthState>
   */
  loginWithNativeFacebook(): firebase.Promise<FirebaseAuthState> {
    return Facebook.login(['email']).then(res => {
      const facebookCredential = firebase.auth.FacebookAuthProvider.credential(res.authResponse.accessToken);
      return firebase.auth().signInWithCredential(facebookCredential);
    });
  }
```
And for prerequise, you need follow http://ionicframework.com/docs/v2/native/facebook/ ;)

After you just have to select correct implementation with `this.platform.is('cordova')`

**Comment by mukesh51** [comment]
@fabien0102 Not sure, what you see as an issue. Could you elaborate more. 
The walk-through document, I've created is to showcase how to integrate AngularFire2 Auth with Ionic2.

I didn't use Ionic-native in the walk-through document and the setup works great and show cases auth usage. Do you think, something more needs to be added in the document ?

**Comment by fabien0102** [comment]
@mukesh51 This document is a great base to implement auth with ionic2 and angularfire but will not work when ionic run out of browser (ionic view, emulator or real app).

My purpose is just to add native alternative in login function (the original issue name was called "Create a walkthrough for Auth on Ionic/Cordova").

You just need transform the actual `signInWithFacebook` function into:
```javascript
import { Platform } from 'ionic-angular';
import { Facebook } from 'ionic-native';
import firebase from 'firebase';

constructor( public platform: Platform, …){
    …
  }

signInWithFacebook(): firebase.Promise < FirebaseAuthState > {
      if(platform.is('cordova')) {
        return Facebook.login(['email']).then(res => {
          const facebookCredential = firebase.auth.FacebookAuthProvider.credential(res.authResponse.accessToken);
          return firebase.auth().signInWithCredential(facebookCredential);
        });
      }else{
        return this.auth$.login({
          provider: AuthProviders.Facebook,
          method: AuthMethods.Popup
        });
      }
    }
```

It’s not easy to find a complete documentation for this part, this PR would have been great when I started ionic :)

**Comment by mukesh51** [comment]
@fabien0102 Good spot. _Appreciate it._ 

I downloaded the corodva facebook plugin and was able to test the application on android phone as well as browser. 

Will update the document as an additional section to make it clear. May be in next few hours.

**Comment by katowulf** [comment]
@mukesh51 thanks for this! Great stuff and a solid contribution.

Could we generalize the title to _Using AngularFire2 with Ionic_? I suspect we'll have more things to add to this in the future. Otherwise, lgtm, and ready to merge.

**Comment by mukesh51** [comment]
Hi @katowulf . Updated the title in both the files. Agree that this file may need updates in future. Also, I've updated the title to  Using AngularFire2 with Ionic2  and not "Ionic", since the way plugins needs to configure for Ionic and Ionic2 is different. Hope this is ok, but let me know, if it needs to be amended.

Thanks

**Pull request merged**
