### PR TITLE
fix(core): only import typing from zone.js

### PR DESCRIPTION
**Pull request by JiaLiPassion**
### Checklist

   - Issue number for this PR: #1597  (required)
   - Docs included?: no (yes/no; required for all API/functional changes) 
   - Test units included?: no (yes/no; required) 
   - In a clean directory, `yarn install`, `yarn test` run successfully? yes (yes/no; required)

### Description

Should only `import {} from 'zone.js'` to import typing, but not import `zone.js` again, otherwise it will report `Zone is already loaded` error.

### Code sample

@jamesdaniels , please review, thank you.

### CODE REVIEW

**Comment by pookdeveloper** [comment]
If I genereta ionic start coference, i get the same error when install de plugin

**Comment by paulstelzer** [comment]
Changing the import did not work for me. I had to remove the complete line to remove the error

**Comment by pookdeveloper** [comment]
@JiaLiPassion  Hellou I only generate the ionic start with template conference, and then install firebase and make the change to 

```
import {} from 'zone.js';
```

try those steps and comment, thanks

**Comment by JiaLiPassion** [comment]
@pookdeveloper , after install `angularfire2` from npm, even you change the src to 
```
import {} from 'zone.js';
```
It will not be loaded into bundle, could you try this zip https://github.com/angular/angularfire2/files/1977627/dist.zip to replace `node_modules/angularfire2/`

**Comment by jamesdaniels** [comment]
Thanks for the fix

**Comment by LRonHubs** [comment]
This zip did not work for me or fix it

**Pull request merged**
