### PR TITLE
Angularfire2 systemjs fix

### PR DESCRIPTION
**Pull request by DiedrikDM**
### Checklist

   - Issue number for this PR: #992  (required)
   - Docs included?: no 
   - Test units included?: no
   - e2e tests included?: no
   - In a clean directory, `npm install`, `npm run build`, and `npm test` run successfully? yes (if I'm not using windows)

### Description

I was able to solve a problem when trying to use angularfire 2 with SystemJS. I created a bundle with rollup containing the index.ts, database.ts and auth.ts exports.
I also needed to create a workaround for SystemJS and firebase. Apparently when you try to load firebase in the bundle with SystemJS, it will wrap the firebase object in a firebase namespace, which breaks the _firebaseAppFactory function. ~~The workaround is to replace firebase.app and firebase.initializeApp to firebase.firebase.app and firebase.firebase.initializeApp respectively. This code is included in the rollup configuration for the bundle.
If someone knows a better way, please let me know!~~
In the SystemJS configuration you need to add a meta configuration part to load firebase as a global variable (see below)

### Code sample

In your SystemJS configuration, use the following "map" and "meta" configuration
```
System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // ...
      // angular libraries and your own code goes here
      // ...
      'angularfire2' : 'npm:angularfire2/bundles/angularfire2.all.umd.js',
      'angularfire2/database' : 'npm:angularfire2/bundles/angularfire2.all.umd.js',
      'angularfire2/auth' : 'npm:angularfire2/bundles/angularfire2.all.umd.js',
      'firebase': 'npm:firebase/firebase.js',
      'firebase/app': 'npm:firebase/firebase.js',
      'firebase/database': 'npm:firebase/firebase.js',
      'firebase/auth': 'npm:firebase/firebase.js'
    },
    meta: {
      firebase : {
        format: 'global',
        exports: 'firebase'
      }
    },
    // other configuration
  })
```

### Disclaimer
Since this is my first contribution to the project, I'm open for any feedback!

#### Edit
Updated the SystemJS.config for the firebase import to be correct

### CODE REVIEW

**Comment by superstarmcawesome** [comment]
Its working great, just one issue I have is that when i try to sign in with a popup/google..
`return this._af.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider()) 
      .catch(error => this._loggly.error('ERROR @ AuthService#signIn() :', error));`

I get an GoogleAuthProvider of undefined.... is this up and running in your app?

**Comment by DiedrikDM** [comment]
@superstarmcawesome nope, it doesn't... Back to the drawing board then I guess...
For the record, if you want a quick solution, in your JS file you can change firebase.auth into firebase.firebase.auth to make it work. 
I guess something is going wrong when importing the firebase library with TypeScript.

**Comment by DiedrikDM** [comment]
@superstarmcawesome I found another (better) solution. The SystemJS config needs to change. I'll need to update the Pull Request as well though.

**Comment by DiedrikDM** [comment]
I've edited the first comment in this PR to have the correct SystemJS configuration. When you add a meta configuration option to load firebase as a global variable, everything starts to come together!

**Comment by superstarmcawesome** [comment]
great! this is working!!! 👍

**Comment by schmitzt3** [comment]
This is awesome @DiedrikDM. Thanks for your contribution - I know this will help quite a few people using SystemJS.

**Comment by davideast** [comment]
Hey @DiedrikDM! Thanks for tackling this issue! I've been swamped and I haven't had enough time to run a proper review. I will get to this soon!

**Comment by Kamshak** [comment]
@davideast hope it's OK to ping you here :) This fix would help a lot with creating a Plunker

**Comment by davideast** [comment]
@DiedrikDM After more research I've learned where the problem lies. 

Your fix does get things working, but it also adds each feature into the main UMD bundle and breaks code splitting.

The issue is with how the `package.json` in each feature's folder references the main UMD bundle. Rather, each feature requires its own UMD bundle. I'm looking into using the structure that Angular uses for each of its feature modules. The [HTTP module](https://github.com/angular/angular/blob/master/packages/http/package.json) is a good example. 

I'll be working on this later next week, and I'll create an issue the details what needs to happen in-depth. If you're still willing to contribute I'd love to have you onboard!

**Comment by salacis** [comment]
For everyone who can't get rid of the 404. Check the filename, I had to rename the *.umd.js removing the `all`. That being said `angularfire2.umd.js` is the final result.

**Comment by salacis** [comment]
I can't compile your fork.

```
> rm -rf dist && tsc && rollup -c rollup.test.config.js

src/database/firebase_list_factory.ts(115,51): error TS2345: Argument of type '(obs: Observer<any[]>) => () => void' is not assignable to parameter of type '(<R>(subscriber: Subscriber<R>) => void | Function | Subscription) | undefined'.
  Type '(obs: Observer<any[]>) => () => void' is not assignable to type '<R>(subscriber: Subscriber<R>) => void | Function | Subscription'.
    Types of parameters 'obs' and 'subscriber' are incompatible.
      Type 'Subscriber<R>' is not assignable to type 'Observer<any[]>'.
        Types of property 'next' are incompatible.
          Type '(value?: R | undefined) => void' is not assignable to type '(value: any[]) => void'.
            Types of parameters 'value' and 'value' are incompatible.
              Type 'any[]' is not assignable to type 'R | undefined'.
                Type 'any[]' is not assignable to type 'R'.
```
Adding your changes to the current master and did the trick, but now it says `Error: No provider for AngularFireAuth!` in browser console.
Shouldn't that already been bundled within the AngularFireModule?

**Comment by DiedrikDM** [comment]
@davideast I can see your point in doing it like that. It will provide with a lot cleaner solution at the end! Can I state though that the current state of this PR can be a short-term workaround for people looking for a solution right now?

To answer your question whether I'm willing to help you guys around? Yes, you can count on me!

**Comment by DiedrikDM** [comment]
@salacis I don't really know what happened with your compilation step. As far as I know, this pull request did not change any files that are being referenced by that build step you mentioned in the error message.

As for the other error message in the browser console: Maybe you need to change to the "build_npm" script instead of the "build" script from package.json? Is your systemjs configuration correct? Do you have the correct files hosted? ... I cannot really tell by the error you're providing me with, but I do hope that I provided you with a direction you can continue your search with!

**Comment by ZuSe** [comment]
Whats the reason for not merging this? Many people that use SystemJS are waiting for this PR and seems to be a suitable workaround for the time till a proper solution is found. As it seems @davideast does not really have the time he needs atm.

**Comment by aamir1995** [comment]
Any news on this? Is this PR is going to be merged into master?

**Comment by davideast** [comment]
@DiedrikDM @ZuSe @aamir1995 

I could merge this in, but it would load 300k of ungzipped code. Also, I'm close to a sending out a PR of the real fix, so I think my time is best focused there. Hold tight, this is my top priority!

**Comment by tobiaseisenschenk** [comment]
I would also highly appreciate this fix, since the workaround did not do it for me and I am currently blocked by this issue.

**Comment by davideast** [comment]
@DiedrikDM @tobiaseisenschenk @ZuSe @aamir1995 

The next release is out! Try installing `npm i angularfire2@next` and see if that works.

**Comment by tobiaseisenschenk** [comment]
Installing the mentioned version results in a low level error for me as shown in the screenshot.
screen shot 2017-08-07 at 9 12 18 am

However before I tried locally downloading the core and database bundles from your systemjs20 feature branch @davideast, which worked except breaking the AOT build.

**Comment by ZuSe** [comment]
I can confirm this.
Fun story. I have compiled the bundles last week my own from your feature branch. They do work for me.
What did you change between Monday last week and the merge?

**Comment by davideast** [comment]
@ZuSe @tobiaseisenschenk 

I'm not 100% sure, but it [may have been this line.](https://github.com/angular/angularfire2/commit/fb58c98668def858edfdde36382cc9746f613f58#diff-df83342fa32260e85e60db4aeadf93beR7)

I needed to import zone.js to bring in the ambient typings. But this may have some ill side-effects for zone users. Can you try removing this line from your local build and see if it works?

**Comment by ZuSe** [comment]
Hi @davideast 
seems to fix the problem. Are you going to push an updated version soon?

**Comment by davideast** [comment]
@ZuSe Yep. I'm not sure how to fix it the right way, but for now I'll change the `Zone` types to `any` because it errors out in the CLI build. If you or anyone knows the real fix, I would love to know it :)

**Comment by jamesdaniels** [comment]
Going to close out this pull request since @davideast has made some progress here. Feel free to continue discussions.

**Comment by davideast** [comment]
@ZuSe @tobiaseisenschenk Can you try installing `angularfire2@next` again and see if that works for you? If so, I'll cut a main release.

**Comment by davideast** [comment]
@DiedrikDM too! ⬆️

**Comment by KrGyan** [comment]
@davideast  . This fixes the issue with AOT and server side rendering.

**Comment by tobiaseisenschenk** [comment]
@davideast somehow there is no database.umd.js bundle anymore?

**Comment by davideast** [comment]
@tobiaseisenschenk Can you try installing again? I just installed it and I see the database UMD.

**Comment by aamir1995** [comment]
@davideast seems like there are separate modules for each Feature, so do we have to require three modules in order to utilize them?  
image

**Comment by tobiaseisenschenk** [comment]
yes, @aamir1995 you need to specify each bundle separately, but you do not need the package meta spec for umd bundles. I only use the core and database e.g.
```
// ANGULARFIRE2 - Core
            {
                name: 'angularfire2',
                path: `${this.NPM_BASE}angularfire2/bundles/core.umd.js`
            },
            // ANGULARFIRE2 - Database
            {
                name: 'angularfire2/database',
                path: `${this.NPM_BASE}angularfire2/bundles/database.umd.js`
            },
```
@davideast It does fix the issue with the AOT build! I overlooked that ```npm install -save angularfire2@next``` puts a ```^``` in my package json, which makes npm resolve it to the next stable version on the next ```npm install``` :)

**Comment by akserg** [comment]
Hi David,

Thank you for your library. 

I used your package in my book [Web Development with Bootstrap 4 and Angular 2 - Second Edition](https://www.packtpub.com/web-development/web-development-bootstrap-4-and-angular-2-second-edition) in chapters 9 and 10. 

I have updated the chapter 9 with `npm install -save angularfire2@next` and it works for SystemJS now. Here is the content of my `systemjs.config.js` file:
```
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler':'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router':'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      // other libraries
      'rxjs': 'npm:rxjs',

      'firebase': 'npm:firebase',
      'promise-polyfill':'npm:promise-polyfill',
                                       
      'angularfire2': 'npm:angularfire2/bundles/core.umd.js',
      'angularfire2/database': 'npm:angularfire2/bundles/database.umd.js',
      'angularfire2/auth': 'npm:angularfire2/bundles/auth.umd.js'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'firebase': { 
        main: 'firebase-browser.js',
        defaultExtension: 'js'
      },
      'promise-polyfill': {
        main: 'promise.js',
        defaultExtension: 'js'
      }
    },
    meta: {
      firebase : {
        format: 'global',
        exports: 'firebase'
      }
    }
  });
})(this);
```

The source code for the full project is [here](https://github.com/akserg/learning_bootstrap4_angular2/tree/master/chapter_9/4.ecommerce-firebase). 

The version ready to deploy on Firebase web hosting [here](https://github.com/akserg/learning_bootstrap4_angular2/tree/master/chapter_9/5.ecommerce-firebase-deploy).

**Please release it soon.**

**Comment by davideast** [comment]
@akserg It was released a few days ago.

**Comment by akserg** [comment]
Ok, thanks.

**Pull request closed without merging**
