### PR TITLE
Allow hmr to work

### PR DESCRIPTION
**Pull request by richtera**
This will allow hmr to re-execute _getFirebase.

### CODE REVIEW

**Comment by richtera** [comment]
Fixed to use app() instead of database().

**Comment by katowulf** [comment]
@richtera looks like the [tests are failing](https://travis-ci.org/angular/angularfire2/builds/160687425), could you ptal and see if you can find a fix?

**Comment by richtera** [comment]
Rebased and force pushed.

**Comment by davideast** [comment]
@richtera Love it! Can you add a section to the guide about setting up HMR with the Angular CLI? It would be great for others to use as well.

**Comment by richtera** [comment]
I can try. I have not used the angular cli. I was cloning and adding to git@github.com:AngularClass/angular2-webpack-starter.git when I ran into the problem.

**Comment by davideast** [comment]
@richtera Ah I see. Even docs on getting it to work with the angular2-webpack-starter would be nice too!

**Comment by richtera** [comment]
Once this module is published in npm it will just work.

**Comment by davideast** [comment]
Hey @richtera. We have some (small) merge conflicts now, can address those or enable edits on your PR?

**Comment by alex88** [comment]
@davideast is this PR good to go? It would be awesome to have it merged

**Comment by ribsies** [comment]
definitely could use this asap!

**Comment by richtera** [comment]
I fixed all the merge conflict but I have not had time to write any docs. Basically you just use the latest code and any webpack with hmr will no longer fail due to multiple initializeApp calls on firebase.

**Comment by alex88** [comment]
I don't think you should write any docs, unless explaining that with multiple calls (that could happend) the subsequent calls are ignored (just in case ppl doesn't know why a config change isn't applied)

**Comment by richtera** [comment]
Ideally, this call should not be made multiple times, but the way hmr reloads classes it will re-execute the constructor and initializeApp for these classes. My code change just catches the exception thrown by firebase when this happens and returning the default app instead. It's not the prettiest of solutions but allows hmr and angularfire2 to live together.

**Comment by ribsies** [comment]
This is how I was getting around it when I was using vanilla firebase. I switched to angular2 fire today assuming it had a better solution. Turns out they don't have any! So I think this is a completely acceptable fix.

**Comment by ribsies** [comment]
This is how I was getting around it when I was using vanilla firebase. I switched to angular2 fire today assuming it had a better solution. Turns out they don't have any! So I think this is a completely acceptable fix.

**Comment by davideast** [comment]
@richtera Thanks for your PR!

**Pull request merged**
