### PR TITLE
small typo fix

### PR DESCRIPTION
**Pull request by ashishpatelcs**
### Checklist

   - Issue number for this PR: #nnn (required)
   - Docs included?: (yes/no; required for all API/functional changes) 
   - Test units included?: (yes/no; required) 
   - In a clean directory, `yarn install`, `yarn test` run successfully? (yes/no; required)

### CODE REVIEW

**Comment by Chan4077** [comment]
@ashishpatelcs Could you create a single PR instead of multiple PRs just on typo fixes?

**Comment by ashishpatelcs** [comment]
@Chan4077 I just found and created them quickly with Github GUI. how do I combine them in a single PR?

**Comment by davideast** [comment]
@ashishpatelcs It is easier to review one PR of small changes and it also will kick off only one CI process instead of 5. If I suggest changes in multiple PRs it will then have to kick off each CI process when you address the changes. When one PR gets merged we'll have to update the next branch and wait for the CI process again to finish. That process repeats with every merge. It's rather time consuming and isn't necessary for small typo fixes.

You can create a fork with the UI and fix the files within that fork. Then create a PR with the UI as well.

**Comment by ashishpatelcs** [comment]
@davideast Thank you so much the detailed explanation. I'll create a new PR soon.

**Pull request closed without merging**
